#!/bin/bash

__run__() {
    [[ -z $1 ]] && {
        echo "ERROR"
        return 1
    }
    cmdFile="$__gb_dir/cmds/$1"

    if [ ! -f "$cmdFile" ] ; then
        cmdFile="$__gb_dir/cmds/$1"
        gb -command-template > $cmdFile

        chmod +x -- $cmdFile
    fi

    vim $cmdFile
}

__complete__() {
    local posss="";
    for path in ${__gb_path//:/ }; do
        posss="$posss $(find $path | sed 's@.*/@@')"
    done

    compgen -W "$posss" -- $CURRENT_TERM
}
