#!/bin/bash

__run__() {
    gb -is-in-repo || return 1

    echo -e "On branch: $(color BLUE $(gb -get-current-branch))"

    echo "Untracked"
    startColor RED
    gb -get-untracked | sed 's/^/   /'
    endColor

    echo "Modified"
    startColor RED
    gb -get-modified | sed 's/^/   /'
    endColor

    echo "Staged to be commited"
    startColor GREEN
    gb -get-staged | sed 's/^/   /'
    endColor
}
