#!/bin/bash

__run__() {
    gb -is-in-repo || return 1

    echo "On branch: $(color BLUE $(gb -get-current-branch))"
    gb -is-detached-head && {
        echo "$(color RED "HEAD is detached")"
    }

    local untrackeds="$(git status -s | grep '^??' | sed 's/^?? */   /')"
    if ! [ -z "$untrackeds" ] ; then
        echo "Untracked"
        startColor RED
        echo "$untrackeds"
        endColor
    fi


    local mods="$(git status -s | grep '^ ' | sed 's/^ */   /')"
    if ! [ -z "$mods" ] ; then
        echo "Modified:-"
        startColor RED
        echo "$mods"
        endColor
    fi

    local stags="$(git status -s | grep '^[^ ?]' | sed 's/^/   /')"
    if ! [ -z "$stags" ] ; then
        echo "Staged $(color GREY "To be commited"):-"
        startColor GREEN
        echo "$stags"
        endColor
    else
        echo $(color YELLOW "No staged changes to be commited")
    fi
}
